[Feature/DT-2315]: Home
DathaPlus/landing-tribologyec pull request #27
Opened 2024-08-27 15:09 UTC by Cristoferfloor

## Jira Link

### [Issue - Go to Jira](https://dathaplus.atlassian.net/browse/EXAMPLE-XXX)

### [Release - Go to Jira](https://dathaplus.atlassian.net/projects/EXAMPLE/versions/XXXXX)

## Tipo de cambios

- [ ] Hotfix (Bug detected)
- [x ] Feature (Issue from an Active Sprint)
- [ ] Release (Release to Jira)

## Pruebas:

- [ ] Unit Test.
- [ ] Coverage.
- [ ] Integration Test.

## Screenshots (Images or video)

| Title                  |       Evidence |
|:-----------------------|---------------:|
| ** Title screenshot ** | ** 
![image](https://github.com/user-attachments/assets/c0f495c3-bf5b-4880-9189-0357132c53c8)
 ** |

2024-08-27 15:10 UTC, danidaniel6462 commented
Task linked: [DT-2315 Actualizar la información del Home](https://app.clickup.com/t/31527430/DT-2315)

2024-08-27 16:19 UTC, elvismpq96 requested changes

2024-08-27 16:19 UTC, elvismpq96 commented on src/app/page.tsx
>        {/* TODO: Obtener los datos desde el admin de Wordpress */}
Quitar el TODO

2024-08-27 16:19 UTC, elvismpq96 commented on src/components/home/products/index.tsx
> +              data={productos}
Nombrar las variables en ingles al igual que los nombres de los archivos

2024-08-28 13:26 UTC, elvismpq96 approved these changes

2024-08-28 13:27 UTC, merged